/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MeuPrimeiroProjeto;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // Primeiros comandos
        System.out.println("Olá mundo!");
        System.out.println("Meu segundo comando de saída");
        
        /** Comentário de documentação. 
        */
    }
}
