/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EstruturaEscolha;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        int codigoProduto = 1;
        
        switch(codigoProduto){
            case 1:
                System.out.println("Pilhas");
                break;
            case 2:
                System.out.println("Canetas");
                break;
            case 3:
                System.out.println("Lápis");
                break;
            default:
                System.out.println("Produto não cadastrado!");
        }
        
    }
}
