/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Heranca;

import java.util.Date;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Vendedor v = new Vendedor();
        v.setNome("Marcio");
        v.setSalario(1000.0f);
        v.setCpf("23723424");
        v.setDataNascimento(new Date());
        v.setComissaoPorItem(10.0f);
        v.setTotalItensVendidos(10);
        
        System.out.println("O salário do vendedor "+v.getNome()+"é: "+v.calcularSalario());
                
        Motorista m = new Motorista();
        
        
    }
}
