/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio24;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    /*
    Ex. 24) Faça um algoritmo que receba 'N' números e mostre positivo, negativo
    ou zero para cada número.
    */
    
    public static void main(String[] args) {
      
        Scanner leitorScanner = new Scanner(System.in);
        
        char desejaContinuar = 'S';
        
        while(desejaContinuar == 'S' || desejaContinuar == 's'){
            System.out.print("Digite um número: ");
            int numero = leitorScanner.nextInt();
            
            if(numero==0){
                System.out.println("O número é ZERO");
            } else {
                if(numero >0){
                    System.out.println("Número POSITIVO.");
                } else{
                    System.out.println("Número NEGATIVO");
                }
            }
            System.out.println("Deseja continuar? [S] para sim / [N] para não");
            desejaContinuar = leitorScanner.next().charAt(0);
        }
        
        System.out.println("Obrigado por utilizar o nosso sistema. Até logo!");
        }
        
    }
